main/urls.py
from django.urls import path
from main.views import create_product_flutter, show_main, create_item, show_xml, show_json, show_xml_by_id, show_json_by_id
from main.views import register, login_user, logout_user
from main.views import increase_amount, decrease_amount, delete_item, edit_item
from main.views import get_product_json, add_item_ajax, delete_item_ajax, edit_item_ajax
app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('create-item/', create_item, name='create_item'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'), 
    path('xml/<int:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>/', show_json_by_id, name='show_json_by_id'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('increase_amount/<int:item_id>/', increase_amount, name='increase_amount'),
    path('decrease_amount/<int:item_id>/', decrease_amount, name='decrease_amount'),
    path('delete-item/<int:item_id>/', delete_item, name='delete_item'),
    path('edit-item/<int:id>', edit_item, name='edit_item'),
    path('get-product/', get_product_json, name='get_product_json'),
    path('create-item-ajax/', add_item_ajax, name='add_item_ajax'),
    path('delete-item-ajax/<int:item_id>/', delete_item_ajax, name='delete_item_ajax'),
    path('edit-item-ajax/<int:item_id>/', edit_item_ajax, name='edit_item_ajax'),
    path('create-flutter/', create_product_flutter, name='create_product_flutter'),
]

peti_library/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
    path('auth/', include('authentication.urls')),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User

class Item(models.Model):
    name = models.CharField(max_length=255)
    date_added = models.DateField(auto_now_add=True)
    amount = models.IntegerField()
    description = models.TextField()
    category = models.CharField(max_length=255)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

# Create your models here.

main/forms.py
from django.forms import ModelForm
from main.models import Item

class ProductForm(ModelForm):
    class Meta:
        model = Item
        fields = ["name", "amount", "description", "category"]

main/views.py
import json
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from main.forms import ProductForm
from main.models import Item
from django.http import HttpResponse, HttpResponseNotFound
from django.core import serializers

import datetime

from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

from django.shortcuts import get_object_or_404
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse
from django.views.decorators.http import require_http_methods


# Create your views here.

@login_required(login_url='/login')
def show_main(request):
    items = Item.objects.filter(user=request.user)

    jumlah_item = items.count()
    context = {
        'name': request.user.username,
        'class': 'PBP A',
        'items': items,
        'jumlah_item' : jumlah_item,
        'last_login': request.COOKIES.get('last_login'),
    }

    return render(request, "main.html", context)

def create_item(request):

    form = ProductForm(request.POST or None)

    if form.is_valid() and request.method == "POST":
        item = form.save(commit=False)
        item.user = request.user
        item.save()
        return HttpResponseRedirect(reverse('main:show_main'))

    context = {'form': form}
    return render(request, "create_product.html", context)

def show_xml(request):
    data = Item.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = Item.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = Item.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json_by_id(request, id):
    data = Item.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been successfully created!')
            return redirect('main:login')
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse("main:show_main")) 
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
        else:
            messages.info(request, 'Sorry, incorrect username or password. Please try again.')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('main:login'))
    response.delete_cookie('last_login')
    return response

def delete_item(request, item_id):
    item = get_object_or_404(Item, pk=item_id)
    item.delete()
    return HttpResponseRedirect(reverse('main:show_main'))

def edit_item(request, id):
    item = Item.objects.get(pk = id)
    form = ProductForm(request.POST or None, instance=item)

    if form.is_valid() and request.method == "POST":
        form.save()
        return HttpResponseRedirect(reverse('main:show_main'))

    context = {'form': form}
    return render(request, "edit_item.html", context)

def get_product_json(request):
    product_item = Item.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize('json', product_item))

@csrf_exempt
def add_item_ajax(request):
    if request.method == 'POST':
        name = request.POST.get("name")
        amount = request.POST.get("amount")
        description = request.POST.get("description")
        category = request.POST.get("category")
        user = request.user

        new_product = Item(name=name, amount=amount, description=description, category=category, user=user)
        new_product.save()

        return HttpResponse(b"CREATED", status=201)

    return HttpResponseNotFound()

@csrf_exempt
def delete_item_ajax(request, item_id):
    if request.method == 'DELETE':
        item = get_object_or_404(Item, pk=item_id)
        item.delete()
        return HttpResponse(b"DELETED", status=200)
    return HttpResponseNotFound()

@csrf_exempt
def increase_amount(request, item_id):
    if request.method == 'POST':
        item = get_object_or_404(Item, pk=item_id)
        item.amount += 1
        item.save()
        return JsonResponse({'status': 'ok', 'amount': item.amount})
    return HttpResponseNotFound()

@csrf_exempt
def decrease_amount(request, item_id):
    if request.method == 'POST':
        item = get_object_or_404(Item, pk=item_id)

        if item.amount > 0:
            item.amount -= 1
            item.save()

        if item.amount == 0:
            item.delete()

        return JsonResponse({'status': 'ok', 'amount': item.amount})
    return HttpResponseNotFound()

@csrf_exempt
def edit_item_ajax(request, item_id):
    item = get_object_or_404(Item, pk=item_id)

    if request.method == "POST":
        form = ProductForm(request.POST, instance=item)
        if form.is_valid():
            form.save()
            return HttpResponse(b"UPDATED", status=200)
        else:
            return HttpResponse(b"ERROR", status=400)

    return JsonResponse(serializers.serialize('json', [item]), safe=False)

@csrf_exempt
def create_product_flutter(request):
    if request.method == 'POST':
        
        data = json.loads(request.body)

        new_product = Item.objects.create(
            user = request.user,
            name = data["name"],
            price = int(data["price"]),
            description = data["description"]
        )

        new_product.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)

main/templates/create_product.html
{% extends 'base.html' %}

{% block content %}
    <style>
        body {
            background-color: #191729;
        }

        .container-box {
            background-color: #f0f0f4;
            max-width: 1200px;
            margin: 50px auto;
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            transition: box-shadow 0.3s ease; 
        }

        .container-box:hover {
            box-shadow: 0 0 20px rgba(0, 0, 0, 0.3); 
        }

        .transparent-btn {
            background-color: rgba(37, 218, 122, 0.5) !important;
            border: none;
            color: #000000;
        }

        .transparent-btn:hover {
            background-color: rgba(170, 151, 151, 0.7) !important;
        }

        .navbar-brand {
            font-weight: bold;
        }

        .btn-delete {
            background-color: #c94b4b !important;
            border: none;
            color: #fff;
        }

        .btn-delete:hover {
            background-color: #9b3838 !important;
        }
    </style>

    <nav class="navbar bg-dark border-bottom border-body" data-bs-theme="dark">
        <div class="container-fluid">
            <a class="navbar-brand">Peti Lib</a>
            <a href="{% url 'main:logout' %}">
                <button class="btn btn-dark" type="button">Logout</button>
            </a>
        </div>
    </nav>

    <div class="container-box">
        <h1 class="text-center">Add New Book</h1>

        <form method="POST">
            {% csrf_token %}
            <table>
                {{ form.as_table }}
                <tr>
                    <td></td>
                    <td>
                        <input type="submit" class="btn btn-secondary btn-sm" value="Add Book"/>
                    </td>
                </tr>
            </table>
        </form>
    </div>
{% endblock content %}

main/templates/edit_item.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<style>
    body {
        background-color: #191729;
    }

    .container-box {
        background-color: #f0f0f4;
        max-width: 1200px;
        margin: 50px auto; 
        padding: 20px;
        border-radius: 10px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1); 
        transition: box-shadow 0.3s ease; 
    }

    .container-box:hover {
        box-shadow: 0 0 20px rgba(0, 0, 0, 0.3);
    }

    .transparent-btn {
        background-color: rgba(37, 218, 122, 0.5) !important; 
        border: none;
        color: #000000;
    }

    .transparent-btn:hover {
        background-color: rgba(170, 151, 151, 0.7) !important;
    }

    .navbar-brand {
        font-weight: bold; 
    }

    .btn-delete {
        background-color: #c94b4b !important; 
        border: none;
        color: #fff;
    }

    .btn-delete:hover {
        background-color: #9b3838 !important; 
    }
</style>

<nav class="navbar bg-dark border-bottom border-body" data-bs-theme="dark">
    <div class="container-fluid">
        <a class="navbar-brand">Peti Lib</a>
        <a href="{% url 'main:logout' %}">
            <button class="btn btn-dark" type="button">Logout</button>
        </a>
    </div>
</nav>

<div class="container-box">
    <h1 class="text-center">Edit Book</h1>

    <form method="POST">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
            <tr>
                <td></td>
                <td>
                    <input type="submit" class="btn btn-secondary btn-sm" value="Edit Book"/>
                </td>
            </tr>
        </table>
    </form>
</div>
{% endblock content %}

main/templates/login.html
{% extends 'base.html' %}

{% block meta %}
    <title>Login</title>
{% endblock meta %}

{% block content %}
    <style>
        body {
            background-color: #191729;
            display: flex;
            align-items: center;
            justify-content: center;
            height: 100vh;
            margin: 0;
        }

        .container-box {
            background-color: #f0f0f4; 
            max-width: 500px;
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            transition: box-shadow 0.3s ease;
        }

        .container-box:hover {
            box-shadow: 0 0 20px rgba(0, 0, 0, 0.3);
        }

        .login-form {
            max-width: 300px;
            margin: 0 auto;
        }

        .form-group {
            margin-bottom: 20px;
        }

        .login-btn {
            background-color: #f5c542;
            border: none;
            color: #000;
            padding: 10px 20px;
            border-radius: 5px;
            cursor: pointer;
            display: block;
            margin: 0 auto;
        }

        .login-btn:hover {
            background-color: #d0ac38;
        }

        .register-link {
            color: #f5c542;
            text-decoration: none;
        }

        .register-link:hover {
            text-decoration: underline;
        }
    </style>

    <div class="container-box login-form">
        <h1 class="text-center">Login</h1>

        <form method="POST" action="">
            {% csrf_token %}
            <div class="form-group">
                <label for="username">Username:</label>
                <input type="text" name="username" id="username" placeholder="Username" class="form-control">
            </div>
            
            <div class="form-group">
                <label for="password">Password:</label>
                <input type="password" name="password" id="password" placeholder="Password" class="form-control">
            </div>

            <div class="form-group">
                <input class="btn login-btn" type="submit" value="Login">
            </div>
        </form>

        {% if messages %}
            <ul>
                {% for message in messages %}
                    <li>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}     
        
        Don't have an account yet? <a href="{% url 'main:register' %}" class="register-link">Register Now</a>
    </div>
{% endblock content %}

main/templates/main.html
{% extends 'base.html' %}

{% block content %}
    <style>
        body {
            background-color: #191729;
        }

        .container-box {
            background-color: #f0f0f4;
            max-width: 1200px;
            margin: 50px auto;
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            transition: box-shadow 0.3s ease;
            overflow: hidden;
            display: flex;
            flex-direction: column;
            min-height: 100vh;
        }

        .container-box:hover {
            box-shadow: 0 0 20px rgba(0, 0, 0, 0.3);
        }

        .transparent-btn {
            background-color: rgba(37, 218, 122, 0.5) !important;
            border: none;
            color: #000000;
        }

        .transparent-btn:hover {
            background-color: rgba(170, 151, 151, 0.7) !important;
        }

        .navbar-brand {
            font-weight: bold;
        }

        .btn-delete {
            background-color: #c94b4b !important;
            border: none;
            color: #fff;
        }

        .btn-delete:hover {
            background-color: #9b3838 !important;
        }

        .card-container {
            margin-bottom: 20px;
        }

        .card {
            width: calc(33.33% - 20px);
            margin-right: 20px;
            margin-bottom: 20px;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            float: left;
        }

        .card-body {
            padding: 15px;
        }

        .card-title {
            font-size: 1rem;
        }

        .card-text {
            font-size: 0.8rem;
        }

        .card-buttons {
            margin-top: 10px;
        }

        .card-buttons button {
            margin-right: 5px;
        }
    </style>

    <nav class="navbar bg-dark border-bottom border-body" data-bs-theme="dark">
        <div class="container-fluid">
            <a class="navbar-brand">Peti Lib</a>
            <a class="navbar-brand"><strong>Welcome, {{name}}!</strong></a>
            <a href="{% url 'main:logout' %}">
                <button class="btn btn-dark" type="button">Logout</button>
            </a>
        </div>
    </nav>

    <div class="container-box">
        <h1 class="text-center">Peti Library's Guide</h1>

        <h5>Name:</h5>
        <p>{{ name }}</p>

        <h5>Class:</h5>
        <p>{{ class }}</p>

        <p>Kamu menyimpan <span id="jumlah_item">{{ jumlah_item }}</span> buku pada aplikasi ini</p>

        <div>
            <div class="card-columns" id="product_cards"></div>

            <div class="card-container"></div>
        </div>


        <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h1 class="modal-title fs-5" id="exampleModalLabel">Add New Book</h1>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <form id="form" onsubmit="return false;">
                            {% csrf_token %}
                            <div class="mb-3">
                                <label for="name" class="col-form-label">Name:</label>
                                <input type="text" class="form-control" id="name" name="name"></input>
                            </div>
                            <div class="mb-3">
                                <label for="amount" class="col-form-label">Amount:</label>
                                <input type="number" class="form-control" id="amount" name="amount"></input>
                            </div>
                            <div class="mb-3">
                                <label for="description" class="col-form-label">Description:</label>
                                <textarea class="form-control" id="description" name="description"></textarea>
                            </div>
                            <div class="mb-3">
                                <label for="category" class="col-form-label">Category:</label>
                                <textarea class="form-control" id="category" name="category"></textarea>
                            </div>
                        </form>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                        <button type="button" class="btn btn-warning" id="button_add" data-bs-dismiss="modal">Add Book</button>
                    </div>
                </div>
            </div>
        </div>

        <div class="modal fade" id="exampleModalEdit" tabindex="-1" aria-labelledby="exampleModalLabelEdit" aria-hidden="true">
            <!-- Modal "Edit" -->
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h1 class="modal-title fs-5" id="exampleModalLabelEdit">Edit Book</h1>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <form id="formEdit" onsubmit="return false;">
                            {% csrf_token %}
                            <div class="mb-3">
                                <label for="nameEdit" class="col-form-label">Name:</label>
                                <input type="text" class="form-control" id="nameEdit" name="nameEdit">
                            </div>
                            <div class="mb-3">
                                <label for="amountEdit" class="col-form-label">Amount:</label>
                                <input type="number" class="form-control" id="amountEdit" name="amountEdit">
                            </div>
                            <div class="mb-3">
                                <label for="descriptionEdit" class="col-form-label">Description:</label>
                                <textarea class="form-control" id="descriptionEdit" name="descriptionEdit"></textarea>
                            </div>
                            <div class="mb-3">
                                <label for="categoryEdit" class="col-form-label">Category:</label>
                                <textarea class="form-control" id="categoryEdit" name="categoryEdit"></textarea>
                            </div>
                        </form>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                        <button type="button" class="btn btn-warning" id="button_edit" data-bs-dismiss="modal">Save Changes</button>
                    </div>
                </div>
            </div>
        </div>
        <br />
        <div class="footer">
            <h6 class="text-right text-muted login-info">Sesi terakhir login: {{ last_login }}</h6>

            <div class="d-flex justify-content-center">
                <button type="button" class="btn btn-warning" data-bs-toggle="modal" data-bs-target="#exampleModal">
                    Add Book by AJAX
                </button>
            </div>

            <div class="d-flex justify-content-center">
                <a href="{% url 'main:create_item' %}" class="btn btn-secondary btn-sm">
                    Add New Book
                </a>
            </div>
        </div>
    </div>

    <script>
        async function getItems() {
            return fetch("{% url 'main:get_product_json' %}").then((res) => res.json());
        }

        async function refreshItems() {
            document.getElementById("product_cards").innerHTML = "";
            const products = await getItems();

            products.forEach((item) => {
                const card = document.createElement('div');
                card.classList.add('card');
                
                card.innerHTML = `
                    <div class="card-body">
                        <h5 class="card-title">${item.fields.name}</h5>
                        <p class="card-text">Amount: ${item.fields.amount}</p>
                        <p class="card-text">Description: ${item.fields.description}</p>
                        <p class="card-text">Category: ${item.fields.category}</p>
                        <p class="card-text">Date Added: ${item.fields.date_added}</p>
                        <div class="d-flex justify-content-between">
                            <button class="btn transparent-btn btn-sm" onclick="increaseAmount(${item.pk})">Increase</button>
                            <button class="btn transparent-btn btn-sm" onclick="decreaseAmount(${item.pk})">Decrease</button>
                            <button class="btn btn-info btn-sm" onclick="editItem(${item.pk})">Edit</button>
                            <button class="btn btn-danger btn-sm" data-url="{% url 'main:delete_item_ajax' 123 %}" onclick="deleteItem(this, ${item.pk})">Delete</button>
                        </div>
                    </div>
                `;

                document.getElementById("product_cards").appendChild(card);
            });
        }

        async function refreshItemCount() {
            const response = await fetch("{% url 'main:get_product_json' %}");
            const products = await response.json();
            const jumlah_item = products.length;

            document.getElementById("jumlah_item").innerText = jumlah_item;
        }

        refreshItems();
        function addItem() {
            fetch("{% url 'main:add_item_ajax' %}", {
                method: "POST",
                body: new FormData(document.querySelector('#form'))
            }).then(() => {
                refreshItems();
                refreshItemCount();
            });
            document.getElementById("form").reset();
            return false;
        }
        document.addEventListener("DOMContentLoaded", refreshItemCount);
        document.getElementById("button_add").onclick = addItem;

        async function increaseAmount(item_id) {
            const response = await fetch(`/increase_amount/${item_id}/`, {
                method: 'POST',
            });

            if (response.status === 200) {
                refreshItems();
                refreshItemCount();
            }
        }

        async function decreaseAmount(item_id) {
            const response = await fetch(`/decrease_amount/${item_id}/`, {
                method: 'POST',
            });

            if (response.status === 200) {
                refreshItems();
                refreshItemCount();
            }
        }

        function deleteItem(button, id) {
            let url = button.getAttribute('data-url').replace('123', id);
            fetch(url, {
                method: "DELETE",
            }).then(() => {
                refreshItems();
                refreshItemCount();
            });
        }

        async function editItem(item_id) {
            const response = await fetch(`/edit-item-ajax/${item_id}/`);
            const item = await response.json();

            // Isi formulir modal "Edit"
            document.getElementById("nameEdit").value = item.fields.name;
            document.getElementById("amountEdit").value = item.fields.amount;
            document.getElementById("descriptionEdit").value = item.fields.description;
            document.getElementById("categoryEdit").value = item.fields.category;

            // Buka modal "Edit"
            $('#exampleModalEdit').modal('show');
        }


    </script>
{% endblock content %}

main/templates/register.html
{% extends 'base.html' %}

{% block meta %}
    <title>Register</title>
{% endblock meta %}

{% block content %}  
    <style>
        body {
            background-color: #191729;
            display: flex;
            align-items: center;
            justify-content: center;
            min-height: 100vh;
            margin: 0;
            padding: 20px;
        }


        .container-box {
            background-color: #f0f0f4;
            width: 80%;
            max-width: 400px;
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            transition: box-shadow 0.3s ease;
            margin: 20px;
        }


        .container-box:hover {
            box-shadow: 0 0 20px rgba(0, 0, 0, 0.3);
        }

        .register-form {
            max-width: 300px;
            margin: 0 auto;
        }

        .form-group {
            margin-bottom: 20px;
        }

        .register-btn {
            background-color: #f5c542;
            border: none;
            color: #000;
            padding: 10px 20px;
            border-radius: 5px;
            cursor: pointer;
            display: block;
            margin: 0 auto;
        }

        .register-btn:hover {
            background-color: #d0ac38;
        }

        .login-link {
            color: #f5c542;
            text-decoration: none;
        }

        .login-link:hover {
            text-decoration: underline;
        }
    </style>

    <div class="container-box register-form">
        <h1 class="text-center">Register</h1>

        <form method="POST">
            {% csrf_token %}
            <div class="form-group">
                {{ form.as_p }}
            </div>

            <div class="form-group">
                <input class="btn register-btn" type="submit" name="submit" value="Daftar">
            </div>
        </form>

        {% if messages %}
            <ul>
                {% for message in messages %}
                    <li>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}

        Already have an account? <a href="{% url 'main:login' %}" class="login-link">Login Now</a>
    </div>
{% endblock content %}